SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') 
AS DATE_FORMAT
FROM BOOK AS T1
LEFT JOIN AUTHOR AS T2 ON T1.AUTHOR_ID = T2.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC
