SELECT T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
FROM REST_INFO AS T1,
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
 FROM REST_INFO GROUP BY FOOD_TYPE) AS T2
WHERE T1.FAVORITES = T2.FAVORITES AND T1.FOOD_TYPE = T2.FOOD_TYPE
ORDER BY FOOD_TYPE DESC
